version: 2
jobs:

  install_and_validate:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - checkout

      - run:
          name: Validate Packer templates
          command: make validate_packer

      - run:
          name: Download Ansible dependencies
          command: make roles
      - run:
          name: Validate Ansible playbooks
          command: make validate_ansible
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_ubuntu16_and_ubuntu14:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      - run:
          name: Build ubuntu16 and ubuntu14 AMIs
          command: |
            export TENANT_ACCOUNTS=$(aws s3 cp --quiet s3://grace-tenant-info/tenant-info/tenants.txt /dev/stdout)
            echo $TENANT_ACCOUNTS
            export USER=$(whoami)
            make ubuntu16
            make ubuntu14
          no_output_timeout: 1h

workflows:
  version: 2

  validate_and_deploy:
    jobs:
      - install_and_validate
      - deploy_ubuntu16_and_ubuntu14:
          filters:
            branches:
              only:
                - master
          requires:
            - install_and_validate
