version: 2
jobs:

  install_and_validate:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - checkout

      - run:
          name: Validate Packer templates
          command: make validate_packer

      - run:
          name: Download Ansible dependencies
          command: make roles
      - run:
          name: Validate Ansible playbooks
          command: make validate_ansible
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_ubuntu16:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      - run:
          name: Build ubuntu16 AMI
          command: |
            export USER=$(whoami)
            make ubuntu16
          no_output_timeout: 1h

workflows:
  version: 2

  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - install_and_validate
      - deploy_ubuntu16:
          filters:
            branches:
              only:
                - master
          requires:
            - install_and_validate

  validate_and_deploy:
    jobs:
      - install_and_validate
      - deploy_ubuntu16:
          filters:
            branches:
              only:
                - master
          requires:
            - install_and_validate
